### PR TITLE
Cache session handle to avoid hitting max session rate-limit.

### PR DESCRIPTION
**Pull request by danmarg**

### CODE REVIEW

**Comment by Linus2punkt0** [comment]
Nice suggestion! I belive it can be simplified somewhat, doing all of the session handling in the bsky_connect-function like so:

`# Setting up connections to bluesky, twitter and mastodon
def bsky_connect():
    session = session_cache_read()
    try:
        bsky = RateLimitedClient()
        if session:
            logger.info("Connecting to Bluesky using saved session.")
            bsky.login(session_string=session)
        else:
            logger.info("Creating new Bluesky session using password and username.")
            bsky.login(BSKY_HANDLE, BSKY_PASSWORD)
            session = bsky.export_session_string()
        session_cache_write(session)
        return bsky
    except Exception as e:
        logger.error(e)
        if e.response.content.error == "RateLimitExceeded":
            ratelimit_reset = e.response.headers["RateLimit-Reset"]
            rate_limit_write(ratelimit_reset)
        exit()`

Then you wouldn't need to do the work of passing the session back and forth, and completely skip any changes to crosspost.py.

Let me know if there is anything I've missed, there might be a reason for doing it another way that I'm not seeing. 
        
 I also think you could remove "cache = {}" and from session_cache_read, and "append_write = "w"" from the end of session_cache_write. 
 
 After that it looks good to merge!

**Comment by Linus2punkt0** [comment]
Hm, it seems this does not handle expired sessions, could that be the case? Meaning if the cached session runs out, it just fails and keeps failing?

**Comment by danmarg** [comment]
That's definitely possible. It seems to be working for me--I didn't realize
sessions eventually expire!--but I have really not read the docs closely. ;)

**Comment by Linus2punkt0** [comment]
I have made a modified version of this PR with some changes that should resolve any issues: https://github.com/Linus2punkt0/bluesky-crossposter/pull/64/files

**Comment by danmarg** [comment]
Thanks, that looks better (at a glance). I will try patching it into my
local copy.

I was going to handle your feedback here but didn't have time. Sorry about
that!

**Pull request closed without merging**
